export const reactions = [
    {
        name: 'Reaction 1',
        value: 1,
        selected: true,
        wells: [
                {
                    reagentName: 'A-Pyridines',
                    structure: './images/structure_1.png',
                    barcode: 'FPR-BS',
                    equivalents: '1',
                    density: '0.234',
                    purity: '16',
                    mmolPerReaction: '0.14',
                    totalReagentNeeded: '2.345',
                    desiredReagentConcentration: '0.2',
                    molecularWeight: '208.192',
                },
                {
                    reagentName: 'B-Pyridines',
                    structure: './images/structure_2.png',
                    barcode: 'FPR-BS',
                    equivalents: '1',
                    density: '0.234',
                    purity: '16',
                    mmolPerReaction: '0.14',
                    totalReagentNeeded: '2.345',
                    desiredReagentConcentration: '0.2',
                    molecularWeight: '208.192',
                },
                {
                    reagentName: 'C-Pyridines',
                    structure: './images/structure_3.png',
                    barcode: 'FPR-BS',
                    equivalents: '1',
                    density: '0.234',
                    purity: '16',
                    mmolPerReaction: '0.14',
                    totalReagentNeeded: '2.345',
                    desiredReagentConcentration: '0.2',
                    molecularWeight: '208.192',
                },
                {
                    reagentName: 'D-Pyridines',
                    structure: './images/structure_4.png',
                    barcode: 'FPR-BS',
                    equivalents: '1',
                    density: '0.234',
                    purity: '16',
                    mmolPerReaction: '0.14',
                    totalReagentNeeded: '2.345',
                    desiredReagentConcentration: '0.2',
                    molecularWeight: '208.192',
                },
                {
                    reagentName: 'E-Pyridines',
                    structure: './images/structure_5.png',
                    barcode: 'FPR-BS',
                    equivalents: '1',
                    density: '0.234',
                    purity: '16',
                    mmolPerReaction: '0.14',
                    totalReagentNeeded: '2.345',
                    desiredReagentConcentration: '0.2',
                    molecularWeight: '208.192',
                },
                {
                    reagentName: 'F-Pyridines',
                    structure: './images/structure_2.png',
                    barcode: 'FPR-BS',
                    equivalents: '1',
                    density: '0.234',
                    purity: '16',
                    mmolPerReaction: '0.14',
                    totalReagentNeeded: '2.345',
                    desiredReagentConcentration: '0.2',
                    molecularWeight: '208.192',
                },
            ]
    },

    {
        name: 'Reaction 2',
        value: 2,
        selected: false,
        wells: [
                {
                    reagentName: 'A-Pyridines',
                    structure: './images/structure_1.png',
                    barcode: 'FPR-BS',
                    equivalents: '1',
                    density: '0.234',
                    purity: '16',
                    mmolPerReaction: '0.14',
                    totalReagentNeeded: '2.345',
                    desiredReagentConcentration: '0.2',
                    molecularWeight: '208.192',
                },
                {
                    reagentName: 'B-Pyridines',
                    structure: './images/structure_2.png',
                    barcode: 'FPR-BS',
                    equivalents: '1',
                    density: '0.234',
                    purity: '16',
                    mmolPerReaction: '0.14',
                    totalReagentNeeded: '2.345',
                    desiredReagentConcentration: '0.2',
                    molecularWeight: '208.192',
                },
                {
                    reagentName: 'C-Pyridines',
                    structure: './images/structure_3.png',
                    barcode: 'FPR-BS',
                    equivalents: '1',
                    density: '0.234',
                    purity: '16',
                    mmolPerReaction: '0.14',
                    totalReagentNeeded: '2.345',
                    desiredReagentConcentration: '0.2',
                    molecularWeight: '208.192',
                },
                {
                    reagentName: 'D-Pyridines',
                    structure: './images/structure_4.png',
                    barcode: 'FPR-BS',
                    equivalents: '1',
                    density: '0.234',
                    purity: '16',
                    mmolPerReaction: '0.14',
                    totalReagentNeeded: '2.345',
                    desiredReagentConcentration: '0.2',
                    molecularWeight: '208.192',
                },
                {
                    reagentName: 'E-Pyridines',
                    structure: './images/structure_5.png',
                    barcode: 'FPR-BS',
                    equivalents: '1',
                    density: '0.234',
                    purity: '16',
                    mmolPerReaction: '0.14',
                    totalReagentNeeded: '2.345',
                    desiredReagentConcentration: '0.2',
                    molecularWeight: '208.192',
                },
                {
                    reagentName: 'F-Pyridines',
                    structure: './images/structure_2.png',
                    barcode: 'FPR-BS',
                    equivalents: '1',
                    density: '0.234',
                    purity: '16',
                    mmolPerReaction: '0.14',
                    totalReagentNeeded: '2.345',
                    desiredReagentConcentration: '0.2',
                    molecularWeight: '208.192',
                },
                {
                    reagentName: 'G-Pyridines',
                    structure: './images/structure_2.png',
                    barcode: 'FPR-BS',
                    equivalents: '1',
                    density: '0.234',
                    purity: '16',
                    mmolPerReaction: '0.14',
                    totalReagentNeeded: '2.345',
                    desiredReagentConcentration: '0.2',
                    molecularWeight: '208.192',
                },
                {
                    reagentName: 'H-Pyridines',
                    structure: './images/structure_2.png',
                    barcode: 'FPR-BS',
                    equivalents: '1',
                    density: '0.234',
                    purity: '16',
                    mmolPerReaction: '0.14',
                    totalReagentNeeded: '2.345',
                    desiredReagentConcentration: '0.2',
                    molecularWeight: '208.192',
                },
                {
                    reagentName: 'I-Pyridines',
                    structure: './images/structure_2.png',
                    barcode: 'FPR-BS',
                    equivalents: '1',
                    density: '0.234',
                    purity: '16',
                    mmolPerReaction: '0.14',
                    totalReagentNeeded: '2.345',
                    desiredReagentConcentration: '0.2',
                    molecularWeight: '208.192',
                },
                {
                    reagentName: 'J-Pyridines',
                    structure: './images/structure_2.png',
                    barcode: 'FPR-BS',
                    equivalents: '1',
                    density: '0.234',
                    purity: '16',
                    mmolPerReaction: '0.14',
                    totalReagentNeeded: '2.345',
                    desiredReagentConcentration: '0.2',
                    molecularWeight: '208.192',
                },
                {
                    reagentName: 'K-Pyridines',
                    structure: './images/structure_2.png',
                    barcode: 'FPR-BS',
                    equivalents: '1',
                    density: '0.234',
                    purity: '16',
                    mmolPerReaction: '0.14',
                    totalReagentNeeded: '2.345',
                    desiredReagentConcentration: '0.2',
                    molecularWeight: '208.192',
                },
            ]
    },
    {
        name: 'Reaction 3',
        value: 3,
        selected: false,
        wells: [
                {
                    reagentName: 'A-Pyridines',
                    structure: './images/structure_1.png',
                    barcode: 'FPR-BS',
                    equivalents: '1',
                    density: '0.234',
                    purity: '16',
                    mmolPerReaction: '0.14',
                    totalReagentNeeded: '2.345',
                    desiredReagentConcentration: '0.2',
                    molecularWeight: '208.192',
                },
                {
                    reagentName: 'B-Pyridines',
                    structure: './images/structure_2.png',
                    barcode: 'FPR-BS',
                    equivalents: '1',
                    density: '0.234',
                    purity: '16',
                    mmolPerReaction: '0.14',
                    totalReagentNeeded: '2.345',
                    desiredReagentConcentration: '0.2',
                    molecularWeight: '208.192',
                },
                {
                    reagentName: 'C-Pyridines',
                    structure: './images/structure_3.png',
                    barcode: 'FPR-BS',
                    equivalents: '1',
                    density: '0.234',
                    purity: '16',
                    mmolPerReaction: '0.14',
                    totalReagentNeeded: '2.345',
                    desiredReagentConcentration: '0.2',
                    molecularWeight: '208.192',
                },
                {
                    reagentName: 'D-Pyridines',
                    structure: './images/structure_4.png',
                    barcode: 'FPR-BS',
                    equivalents: '1',
                    density: '0.234',
                    purity: '16',
                    mmolPerReaction: '0.14',
                    totalReagentNeeded: '2.345',
                    desiredReagentConcentration: '0.2',
                    molecularWeight: '208.192',
                },
                {
                    reagentName: 'E-Pyridines',
                    structure: './images/structure_5.png',
                    barcode: 'FPR-BS',
                    equivalents: '1',
                    density: '0.234',
                    purity: '16',
                    mmolPerReaction: '0.14',
                    totalReagentNeeded: '2.345',
                    desiredReagentConcentration: '0.2',
                    molecularWeight: '208.192',
                },
                {
                    reagentName: 'F-Pyridines',
                    structure: './images/structure_2.png',
                    barcode: 'FPR-BS',
                    equivalents: '1',
                    density: '0.234',
                    purity: '16',
                    mmolPerReaction: '0.14',
                    totalReagentNeeded: '2.345',
                    desiredReagentConcentration: '0.2',
                    molecularWeight: '208.192',
                },
                {
                    reagentName: 'G-Pyridines',
                    structure: './images/structure_2.png',
                    barcode: 'FPR-BS',
                    equivalents: '1',
                    density: '0.234',
                    purity: '16',
                    mmolPerReaction: '0.14',
                    totalReagentNeeded: '2.345',
                    desiredReagentConcentration: '0.2',
                    molecularWeight: '208.192',
                },
                {
                    reagentName: 'H-Pyridines',
                    structure: './images/structure_2.png',
                    barcode: 'FPR-BS',
                    equivalents: '1',
                    density: '0.234',
                    purity: '16',
                    mmolPerReaction: '0.14',
                    totalReagentNeeded: '2.345',
                    desiredReagentConcentration: '0.2',
                    molecularWeight: '208.192',
                },
                {
                    reagentName: 'I-Pyridines',
                    structure: './images/structure_2.png',
                    barcode: 'FPR-BS',
                    equivalents: '1',
                    density: '0.234',
                    purity: '16',
                    mmolPerReaction: '0.14',
                    totalReagentNeeded: '2.345',
                    desiredReagentConcentration: '0.2',
                    molecularWeight: '208.192',
                },
                {
                    reagentName: 'J-Pyridines',
                    structure: './images/structure_2.png',
                    barcode: 'FPR-BS',
                    equivalents: '1',
                    density: '0.234',
                    purity: '16',
                    mmolPerReaction: '0.14',
                    totalReagentNeeded: '2.345',
                    desiredReagentConcentration: '0.2',
                    molecularWeight: '208.192',
                },
                {
                    reagentName: 'K-Pyridines',
                    structure: './images/structure_2.png',
                    barcode: 'FPR-BS',
                    equivalents: '1',
                    density: '0.234',
                    purity: '16',
                    mmolPerReaction: '0.14',
                    totalReagentNeeded: '2.345',
                    desiredReagentConcentration: '0.2',
                    molecularWeight: '208.192',
                },
                {
                    reagentName: 'K-Pyridines',
                    structure: './images/structure_2.png',
                    barcode: 'FPR-BS',
                    equivalents: '1',
                    density: '0.234',
                    purity: '16',
                    mmolPerReaction: '0.14',
                    totalReagentNeeded: '2.345',
                    desiredReagentConcentration: '0.2',
                    molecularWeight: '208.192',
                },
                {
                    reagentName: 'K-Pyridines',
                    structure: './images/structure_2.png',
                    barcode: 'FPR-BS',
                    equivalents: '1',
                    density: '0.234',
                    purity: '16',
                    mmolPerReaction: '0.14',
                    totalReagentNeeded: '2.345',
                    desiredReagentConcentration: '0.2',
                    molecularWeight: '208.192',
                },
                {
                    reagentName: 'K-Pyridines',
                    structure: './images/structure_2.png',
                    barcode: 'FPR-BS',
                    equivalents: '1',
                    density: '0.234',
                    purity: '16',
                    mmolPerReaction: '0.14',
                    totalReagentNeeded: '2.345',
                    desiredReagentConcentration: '0.2',
                    molecularWeight: '208.192',
                },
                {
                    reagentName: 'K-Pyridines',
                    structure: './images/structure_2.png',
                    barcode: 'FPR-BS',
                    equivalents: '1',
                    density: '0.234',
                    purity: '16',
                    mmolPerReaction: '0.14',
                    totalReagentNeeded: '2.345',
                    desiredReagentConcentration: '0.2',
                    molecularWeight: '208.192',
                },
                {
                    reagentName: 'K-Pyridines',
                    structure: './images/structure_2.png',
                    barcode: 'FPR-BS',
                    equivalents: '1',
                    density: '0.234',
                    purity: '16',
                    mmolPerReaction: '0.14',
                    totalReagentNeeded: '2.345',
                    desiredReagentConcentration: '0.2',
                    molecularWeight: '208.192',
                },
                {
                    reagentName: 'K-Pyridines',
                    structure: './images/structure_2.png',
                    barcode: 'FPR-BS',
                    equivalents: '1',
                    density: '0.234',
                    purity: '16',
                    mmolPerReaction: '0.14',
                    totalReagentNeeded: '2.345',
                    desiredReagentConcentration: '0.2',
                    molecularWeight: '208.192',
                },
                {
                    reagentName: 'K-Pyridines',
                    structure: './images/structure_2.png',
                    barcode: 'FPR-BS',
                    equivalents: '1',
                    density: '0.234',
                    purity: '16',
                    mmolPerReaction: '0.14',
                    totalReagentNeeded: '2.345',
                    desiredReagentConcentration: '0.2',
                    molecularWeight: '208.192',
                },
                {
                    reagentName: 'K-Pyridines',
                    structure: './images/structure_2.png',
                    barcode: 'FPR-BS',
                    equivalents: '1',
                    density: '0.234',
                    purity: '16',
                    mmolPerReaction: '0.14',
                    totalReagentNeeded: '2.345',
                    desiredReagentConcentration: '0.2',
                    molecularWeight: '208.192',
                },
                {
                    reagentName: 'K-Pyridines',
                    structure: './images/structure_2.png',
                    barcode: 'FPR-BS',
                    equivalents: '1',
                    density: '0.234',
                    purity: '16',
                    mmolPerReaction: '0.14',
                    totalReagentNeeded: '2.345',
                    desiredReagentConcentration: '0.2',
                    molecularWeight: '208.192',
                },
                {
                    reagentName: 'K-Pyridines',
                    structure: './images/structure_2.png',
                    barcode: 'FPR-BS',
                    equivalents: '1',
                    density: '0.234',
                    purity: '16',
                    mmolPerReaction: '0.14',
                    totalReagentNeeded: '2.345',
                    desiredReagentConcentration: '0.2',
                    molecularWeight: '208.192',
                },
                {
                    reagentName: 'K-Pyridines',
                    structure: './images/structure_2.png',
                    barcode: 'FPR-BS',
                    equivalents: '1',
                    density: '0.234',
                    purity: '16',
                    mmolPerReaction: '0.14',
                    totalReagentNeeded: '2.345',
                    desiredReagentConcentration: '0.2',
                    molecularWeight: '208.192',
                },
                {
                    reagentName: 'K-Pyridines',
                    structure: './images/structure_2.png',
                    barcode: 'FPR-BS',
                    equivalents: '1',
                    density: '0.234',
                    purity: '16',
                    mmolPerReaction: '0.14',
                    totalReagentNeeded: '2.345',
                    desiredReagentConcentration: '0.2',
                    molecularWeight: '208.192',
                },
                {
                    reagentName: 'K-Pyridines',
                    structure: './images/structure_2.png',
                    barcode: 'FPR-BS',
                    equivalents: '1',
                    density: '0.234',
                    purity: '16',
                    mmolPerReaction: '0.14',
                    totalReagentNeeded: '2.345',
                    desiredReagentConcentration: '0.2',
                    molecularWeight: '208.192',
                },
                {
                    reagentName: 'K-Pyridines',
                    structure: './images/structure_2.png',
                    barcode: 'FPR-BS',
                    equivalents: '1',
                    density: '0.234',
                    purity: '16',
                    mmolPerReaction: '0.14',
                    totalReagentNeeded: '2.345',
                    desiredReagentConcentration: '0.2',
                    molecularWeight: '208.192',
                },
                {
                    reagentName: 'K-Pyridines',
                    structure: './images/structure_2.png',
                    barcode: 'FPR-BS',
                    equivalents: '1',
                    density: '0.234',
                    purity: '16',
                    mmolPerReaction: '0.14',
                    totalReagentNeeded: '2.345',
                    desiredReagentConcentration: '0.2',
                    molecularWeight: '208.192',
                },
                {
                    reagentName: 'K-Pyridines',
                    structure: './images/structure_2.png',
                    barcode: 'FPR-BS',
                    equivalents: '1',
                    density: '0.234',
                    purity: '16',
                    mmolPerReaction: '0.14',
                    totalReagentNeeded: '2.345',
                    desiredReagentConcentration: '0.2',
                    molecularWeight: '208.192',
                },
                {
                    reagentName: 'K-Pyridines',
                    structure: './images/structure_2.png',
                    barcode: 'FPR-BS',
                    equivalents: '1',
                    density: '0.234',
                    purity: '16',
                    mmolPerReaction: '0.14',
                    totalReagentNeeded: '2.345',
                    desiredReagentConcentration: '0.2',
                    molecularWeight: '208.192',
                },
                {
                    reagentName: 'K-Pyridines',
                    structure: './images/structure_2.png',
                    barcode: 'FPR-BS',
                    equivalents: '1',
                    density: '0.234',
                    purity: '16',
                    mmolPerReaction: '0.14',
                    totalReagentNeeded: '2.345',
                    desiredReagentConcentration: '0.2',
                    molecularWeight: '208.192',
                },
                {
                    reagentName: 'K-Pyridines',
                    structure: './images/structure_2.png',
                    barcode: 'FPR-BS',
                    equivalents: '1',
                    density: '0.234',
                    purity: '16',
                    mmolPerReaction: '0.14',
                    totalReagentNeeded: '2.345',
                    desiredReagentConcentration: '0.2',
                    molecularWeight: '208.192',
                },
                {
                    reagentName: 'K-Pyridines',
                    structure: './images/structure_2.png',
                    barcode: 'FPR-BS',
                    equivalents: '1',
                    density: '0.234',
                    purity: '16',
                    mmolPerReaction: '0.14',
                    totalReagentNeeded: '2.345',
                    desiredReagentConcentration: '0.2',
                    molecularWeight: '208.192',
                },
                {
                    reagentName: 'K-Pyridines',
                    structure: './images/structure_2.png',
                    barcode: 'FPR-BS',
                    equivalents: '1',
                    density: '0.234',
                    purity: '16',
                    mmolPerReaction: '0.14',
                    totalReagentNeeded: '2.345',
                    desiredReagentConcentration: '0.2',
                    molecularWeight: '208.192',
                },
                {
                    reagentName: 'K-Pyridines',
                    structure: './images/structure_2.png',
                    barcode: 'FPR-BS',
                    equivalents: '1',
                    density: '0.234',
                    purity: '16',
                    mmolPerReaction: '0.14',
                    totalReagentNeeded: '2.345',
                    desiredReagentConcentration: '0.2',
                    molecularWeight: '208.192',
                },
                {
                    reagentName: 'K-Pyridines',
                    structure: './images/structure_2.png',
                    barcode: 'FPR-BS',
                    equivalents: '1',
                    density: '0.234',
                    purity: '16',
                    mmolPerReaction: '0.14',
                    totalReagentNeeded: '2.345',
                    desiredReagentConcentration: '0.2',
                    molecularWeight: '208.192',
                },
                {
                    reagentName: 'K-Pyridines',
                    structure: './images/structure_2.png',
                    barcode: 'FPR-BS',
                    equivalents: '1',
                    density: '0.234',
                    purity: '16',
                    mmolPerReaction: '0.14',
                    totalReagentNeeded: '2.345',
                    desiredReagentConcentration: '0.2',
                    molecularWeight: '208.192',
                },
                {
                    reagentName: 'K-Pyridines',
                    structure: './images/structure_2.png',
                    barcode: 'FPR-BS',
                    equivalents: '1',
                    density: '0.234',
                    purity: '16',
                    mmolPerReaction: '0.14',
                    totalReagentNeeded: '2.345',
                    desiredReagentConcentration: '0.2',
                    molecularWeight: '208.192',
                },
                {
                    reagentName: 'K-Pyridines',
                    structure: './images/structure_2.png',
                    barcode: 'FPR-BS',
                    equivalents: '1',
                    density: '0.234',
                    purity: '16',
                    mmolPerReaction: '0.14',
                    totalReagentNeeded: '2.345',
                    desiredReagentConcentration: '0.2',
                    molecularWeight: '208.192',
                },
                {
                    reagentName: 'K-Pyridines',
                    structure: './images/structure_2.png',
                    barcode: 'FPR-BS',
                    equivalents: '1',
                    density: '0.234',
                    purity: '16',
                    mmolPerReaction: '0.14',
                    totalReagentNeeded: '2.345',
                    desiredReagentConcentration: '0.2',
                    molecularWeight: '208.192',
                },
                {
                    reagentName: 'K-Pyridines',
                    structure: './images/structure_2.png',
                    barcode: 'FPR-BS',
                    equivalents: '1',
                    density: '0.234',
                    purity: '16',
                    mmolPerReaction: '0.14',
                    totalReagentNeeded: '2.345',
                    desiredReagentConcentration: '0.2',
                    molecularWeight: '208.192',
                },
                {
                    reagentName: 'K-Pyridines',
                    structure: './images/structure_2.png',
                    barcode: 'FPR-BS',
                    equivalents: '1',
                    density: '0.234',
                    purity: '16',
                    mmolPerReaction: '0.14',
                    totalReagentNeeded: '2.345',
                    desiredReagentConcentration: '0.2',
                    molecularWeight: '208.192',
                },
                {
                    reagentName: 'K-Pyridines',
                    structure: './images/structure_2.png',
                    barcode: 'FPR-BS',
                    equivalents: '1',
                    density: '0.234',
                    purity: '16',
                    mmolPerReaction: '0.14',
                    totalReagentNeeded: '2.345',
                    desiredReagentConcentration: '0.2',
                    molecularWeight: '208.192',
                },
                {
                    reagentName: 'K-Pyridines',
                    structure: './images/structure_2.png',
                    barcode: 'FPR-BS',
                    equivalents: '1',
                    density: '0.234',
                    purity: '16',
                    mmolPerReaction: '0.14',
                    totalReagentNeeded: '2.345',
                    desiredReagentConcentration: '0.2',
                    molecularWeight: '208.192',
                },
                {
                    reagentName: 'K-Pyridines',
                    structure: './images/structure_2.png',
                    barcode: 'FPR-BS',
                    equivalents: '1',
                    density: '0.234',
                    purity: '16',
                    mmolPerReaction: '0.14',
                    totalReagentNeeded: '2.345',
                    desiredReagentConcentration: '0.2',
                    molecularWeight: '208.192',
                },
                {
                    reagentName: 'K-Pyridines',
                    structure: './images/structure_2.png',
                    barcode: 'FPR-BS',
                    equivalents: '1',
                    density: '0.234',
                    purity: '16',
                    mmolPerReaction: '0.14',
                    totalReagentNeeded: '2.345',
                    desiredReagentConcentration: '0.2',
                    molecularWeight: '208.192',
                },
                {
                    reagentName: 'K-Pyridines',
                    structure: './images/structure_2.png',
                    barcode: 'FPR-BS',
                    equivalents: '1',
                    density: '0.234',
                    purity: '16',
                    mmolPerReaction: '0.14',
                    totalReagentNeeded: '2.345',
                    desiredReagentConcentration: '0.2',
                    molecularWeight: '208.192',
                },
                {
                    reagentName: 'K-Pyridines',
                    structure: './images/structure_2.png',
                    barcode: 'FPR-BS',
                    equivalents: '1',
                    density: '0.234',
                    purity: '16',
                    mmolPerReaction: '0.14',
                    totalReagentNeeded: '2.345',
                    desiredReagentConcentration: '0.2',
                    molecularWeight: '208.192',
                },
                {
                    reagentName: 'K-Pyridines',
                    structure: './images/structure_2.png',
                    barcode: 'FPR-BS',
                    equivalents: '1',
                    density: '0.234',
                    purity: '16',
                    mmolPerReaction: '0.14',
                    totalReagentNeeded: '2.345',
                    desiredReagentConcentration: '0.2',
                    molecularWeight: '208.192',
                },
                {
                    reagentName: 'K-Pyridines',
                    structure: './images/structure_2.png',
                    barcode: 'FPR-BS',
                    equivalents: '1',
                    density: '0.234',
                    purity: '16',
                    mmolPerReaction: '0.14',
                    totalReagentNeeded: '2.345',
                    desiredReagentConcentration: '0.2',
                    molecularWeight: '208.192',
                },
                {
                    reagentName: 'K-Pyridines',
                    structure: './images/structure_2.png',
                    barcode: 'FPR-BS',
                    equivalents: '1',
                    density: '0.234',
                    purity: '16',
                    mmolPerReaction: '0.14',
                    totalReagentNeeded: '2.345',
                    desiredReagentConcentration: '0.2',
                    molecularWeight: '208.192',
                },
                {
                    reagentName: 'K-Pyridines',
                    structure: './images/structure_2.png',
                    barcode: 'FPR-BS',
                    equivalents: '1',
                    density: '0.234',
                    purity: '16',
                    mmolPerReaction: '0.14',
                    totalReagentNeeded: '2.345',
                    desiredReagentConcentration: '0.2',
                    molecularWeight: '208.192',
                },
                {
                    reagentName: 'K-Pyridines',
                    structure: './images/structure_2.png',
                    barcode: 'FPR-BS',
                    equivalents: '1',
                    density: '0.234',
                    purity: '16',
                    mmolPerReaction: '0.14',
                    totalReagentNeeded: '2.345',
                    desiredReagentConcentration: '0.2',
                    molecularWeight: '208.192',
                },
                {
                    reagentName: 'K-Pyridines',
                    structure: './images/structure_2.png',
                    barcode: 'FPR-BS',
                    equivalents: '1',
                    density: '0.234',
                    purity: '16',
                    mmolPerReaction: '0.14',
                    totalReagentNeeded: '2.345',
                    desiredReagentConcentration: '0.2',
                    molecularWeight: '208.192',
                },
                {
                    reagentName: 'K-Pyridines',
                    structure: './images/structure_2.png',
                    barcode: 'FPR-BS',
                    equivalents: '1',
                    density: '0.234',
                    purity: '16',
                    mmolPerReaction: '0.14',
                    totalReagentNeeded: '2.345',
                    desiredReagentConcentration: '0.2',
                    molecularWeight: '208.192',
                },
                {
                    reagentName: 'K-Pyridines',
                    structure: './images/structure_2.png',
                    barcode: 'FPR-BS',
                    equivalents: '1',
                    density: '0.234',
                    purity: '16',
                    mmolPerReaction: '0.14',
                    totalReagentNeeded: '2.345',
                    desiredReagentConcentration: '0.2',
                    molecularWeight: '208.192',
                },
                {
                    reagentName: 'K-Pyridines',
                    structure: './images/structure_2.png',
                    barcode: 'FPR-BS',
                    equivalents: '1',
                    density: '0.234',
                    purity: '16',
                    mmolPerReaction: '0.14',
                    totalReagentNeeded: '2.345',
                    desiredReagentConcentration: '0.2',
                    molecularWeight: '208.192',
                },
                {
                    reagentName: 'K-Pyridines',
                    structure: './images/structure_2.png',
                    barcode: 'FPR-BS',
                    equivalents: '1',
                    density: '0.234',
                    purity: '16',
                    mmolPerReaction: '0.14',
                    totalReagentNeeded: '2.345',
                    desiredReagentConcentration: '0.2',
                    molecularWeight: '208.192',
                },
                {
                    reagentName: 'K-Pyridines',
                    structure: './images/structure_2.png',
                    barcode: 'FPR-BS',
                    equivalents: '1',
                    density: '0.234',
                    purity: '16',
                    mmolPerReaction: '0.14',
                    totalReagentNeeded: '2.345',
                    desiredReagentConcentration: '0.2',
                    molecularWeight: '208.192',
                },
                {
                    reagentName: 'K-Pyridines',
                    structure: './images/structure_2.png',
                    barcode: 'FPR-BS',
                    equivalents: '1',
                    density: '0.234',
                    purity: '16',
                    mmolPerReaction: '0.14',
                    totalReagentNeeded: '2.345',
                    desiredReagentConcentration: '0.2',
                    molecularWeight: '208.192',
                },
                {
                    reagentName: 'K-Pyridines',
                    structure: './images/structure_2.png',
                    barcode: 'FPR-BS',
                    equivalents: '1',
                    density: '0.234',
                    purity: '16',
                    mmolPerReaction: '0.14',
                    totalReagentNeeded: '2.345',
                    desiredReagentConcentration: '0.2',
                    molecularWeight: '208.192',
                },
                {
                    reagentName: 'K-Pyridines',
                    structure: './images/structure_2.png',
                    barcode: 'FPR-BS',
                    equivalents: '1',
                    density: '0.234',
                    purity: '16',
                    mmolPerReaction: '0.14',
                    totalReagentNeeded: '2.345',
                    desiredReagentConcentration: '0.2',
                    molecularWeight: '208.192',
                },
                {
                    reagentName: 'K-Pyridines',
                    structure: './images/structure_2.png',
                    barcode: 'FPR-BS',
                    equivalents: '1',
                    density: '0.234',
                    purity: '16',
                    mmolPerReaction: '0.14',
                    totalReagentNeeded: '2.345',
                    desiredReagentConcentration: '0.2',
                    molecularWeight: '208.192',
                },
                {
                    reagentName: 'K-Pyridines',
                    structure: './images/structure_2.png',
                    barcode: 'FPR-BS',
                    equivalents: '1',
                    density: '0.234',
                    purity: '16',
                    mmolPerReaction: '0.14',
                    totalReagentNeeded: '2.345',
                    desiredReagentConcentration: '0.2',
                    molecularWeight: '208.192',
                },
                {
                    reagentName: 'K-Pyridines',
                    structure: './images/structure_2.png',
                    barcode: 'FPR-BS',
                    equivalents: '1',
                    density: '0.234',
                    purity: '16',
                    mmolPerReaction: '0.14',
                    totalReagentNeeded: '2.345',
                    desiredReagentConcentration: '0.2',
                    molecularWeight: '208.192',
                },
                {
                    reagentName: 'K-Pyridines',
                    structure: './images/structure_2.png',
                    barcode: 'FPR-BS',
                    equivalents: '1',
                    density: '0.234',
                    purity: '16',
                    mmolPerReaction: '0.14',
                    totalReagentNeeded: '2.345',
                    desiredReagentConcentration: '0.2',
                    molecularWeight: '208.192',
                },
                {
                    reagentName: 'K-Pyridines',
                    structure: './images/structure_2.png',
                    barcode: 'FPR-BS',
                    equivalents: '1',
                    density: '0.234',
                    purity: '16',
                    mmolPerReaction: '0.14',
                    totalReagentNeeded: '2.345',
                    desiredReagentConcentration: '0.2',
                    molecularWeight: '208.192',
                },
                {
                    reagentName: 'K-Pyridines',
                    structure: './images/structure_2.png',
                    barcode: 'FPR-BS',
                    equivalents: '1',
                    density: '0.234',
                    purity: '16',
                    mmolPerReaction: '0.14',
                    totalReagentNeeded: '2.345',
                    desiredReagentConcentration: '0.2',
                    molecularWeight: '208.192',
                },
                {
                    reagentName: 'K-Pyridines',
                    structure: './images/structure_2.png',
                    barcode: 'FPR-BS',
                    equivalents: '1',
                    density: '0.234',
                    purity: '16',
                    mmolPerReaction: '0.14',
                    totalReagentNeeded: '2.345',
                    desiredReagentConcentration: '0.2',
                    molecularWeight: '208.192',
                },
                {
                    reagentName: 'K-Pyridines',
                    structure: './images/structure_2.png',
                    barcode: 'FPR-BS',
                    equivalents: '1',
                    density: '0.234',
                    purity: '16',
                    mmolPerReaction: '0.14',
                    totalReagentNeeded: '2.345',
                    desiredReagentConcentration: '0.2',
                    molecularWeight: '208.192',
                },
                {
                    reagentName: 'K-Pyridines',
                    structure: './images/structure_2.png',
                    barcode: 'FPR-BS',
                    equivalents: '1',
                    density: '0.234',
                    purity: '16',
                    mmolPerReaction: '0.14',
                    totalReagentNeeded: '2.345',
                    desiredReagentConcentration: '0.2',
                    molecularWeight: '208.192',
                },
                {
                    reagentName: 'K-Pyridines',
                    structure: './images/structure_2.png',
                    barcode: 'FPR-BS',
                    equivalents: '1',
                    density: '0.234',
                    purity: '16',
                    mmolPerReaction: '0.14',
                    totalReagentNeeded: '2.345',
                    desiredReagentConcentration: '0.2',
                    molecularWeight: '208.192',
                },
                {
                    reagentName: 'K-Pyridines',
                    structure: './images/structure_2.png',
                    barcode: 'FPR-BS',
                    equivalents: '1',
                    density: '0.234',
                    purity: '16',
                    mmolPerReaction: '0.14',
                    totalReagentNeeded: '2.345',
                    desiredReagentConcentration: '0.2',
                    molecularWeight: '208.192',
                },
                {
                    reagentName: 'K-Pyridines',
                    structure: './images/structure_2.png',
                    barcode: 'FPR-BS',
                    equivalents: '1',
                    density: '0.234',
                    purity: '16',
                    mmolPerReaction: '0.14',
                    totalReagentNeeded: '2.345',
                    desiredReagentConcentration: '0.2',
                    molecularWeight: '208.192',
                },
                {
                    reagentName: 'K-Pyridines',
                    structure: './images/structure_2.png',
                    barcode: 'FPR-BS',
                    equivalents: '1',
                    density: '0.234',
                    purity: '16',
                    mmolPerReaction: '0.14',
                    totalReagentNeeded: '2.345',
                    desiredReagentConcentration: '0.2',
                    molecularWeight: '208.192',
                },

            ]
    }
];